---
title: "Visualisations"
author: "Luke Hardwick, Adam Smit, Jess Part"
date: "2023-11-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("tidyverse")
library("tidymodels")
library("xlsx")
```


```{r vis, out.width="100%"}

# Crimes_Region_County <- xlsx::read.xlsx("data/CSV/Crimes_by_County-Region.xlsx", sheetIndex = 4)
# Crimes_Region_County <- na.omit(Crimes_Region_County)
# colnames(Crimes_Region_County) <- Crimes_Region_County[1,]
# Crimes_Region_County <- Crimes_Region_County[-c(1,2,3),]
# 
# col_int <- c(4,10,11,12,21,22,23,24,25)
# col_names <- c("Violence against the person", "Sexual offences", "Robbery", "Theft offences", 
#                "Criminal damage and arson", "Drug offences", "Possesion of weapons offences", 
#                "Public order offences", "Miscellaneous crimes") 
# 
# County_names <- Crimes_Region_County %>%
#   filter(substr(`Area Code`, 1, 2) == "E2")
# 
# Region_names <- Crimes_Region_County %>% 
#   filter(substr(`Area Code`, 1, 2) == "E1")
# 
# Region_names <- Region_names[2]
# Region_names <- Region_names[,"Area Name"]
# County_names <- County_names[2]
# County_names <- County_names[,"Area Name"]
# 
# #Removes Violence and theft breakdown
# Crimes_Region_County <- Crimes_Region_County[-c(5:9, 13:20)]
# 
# 
# for(i in Region_names)
# {
#   
#   crimes <- Crimes_Region_County %>% filter(`Area Name` == i)
#   crimes <- crimes[c(1),]
#   crimes <- crimes[-c(1,2,3)]
#   
#   df <- data.frame(matrix(ncol = 2, nrow = length(col_names)) )
#   colnames(df) <- c("Crime", "Occurrences")
#   
#   for( j in c(1:length(col_names)) )
#   {
#     df[j,] <- c(col_names[j], as.numeric(crimes[j]))
#   }
#   
#   df$Occurrences <- as.numeric(df$Occurrences)
# 
#   print(ggplot(df, aes(x = Crime, y = Occurrences, fill = Crime) ) + 
#          geom_bar(stat = "identity") +
#   scale_x_discrete(guide = guide_axis(n.dodge = 5)) + 
#     labs(
#       title = paste("Crime in", i)
#     ))
# 
# }

## A lot of the code is just mutating the local authority names so that they all match up when joining
####### Crime Rate 
Crimes_Region_County_Per <- xlsx::read.xlsx("data/CSV/Crimes_by_County-Region.xlsx", sheetIndex = 6)
Crimes_Region_County_Per <- na.omit(Crimes_Region_County_Per)
colnames(Crimes_Region_County_Per) <- Crimes_Region_County_Per[1,]
Crimes_Region_County_Per <- Crimes_Region_County_Per[-c(1,2,3),]

Crimes_Region_County_Per <- Crimes_Region_County_Per %>%
  filter( substr(`Area Code`, 1, 2) == "E2")

Crimes_Region_County_Per <- Crimes_Region_County_Per[c(2, 5)]

colnames(Crimes_Region_County_Per) <- c("County", "Crime rate (per 1000)")

####### Mean income

Economic <- readODS::read_ods("data/CSV/Economic_Stats.ods", sheet = 2)
Economic <- na.omit(Economic)
colnames(Economic) <- Economic[1,]
Economic <- Economic[-c(1,2,3),]

Economic <- Economic %>% 
  filter(substr(`Region / County codes`, 1, 3) != "E12" & substr(`Region / County codes`, 1, 2) == "E1")

Economic <- Economic[c(2, 16, 17)]
colnames(Economic) <- c("County", colnames(Economic)[2], colnames(Economic)[3])

df <- left_join(Crimes_Region_County_Per, Economic, by = "County")
df <- na.omit(df)
df <- arrange(df, desc(`Total income: Mean`))
df$`Crime rate (per 1000)` <- as.numeric(df$`Crime rate (per 1000)`)

### Mean income vs crime rate

ggplot(data = df, mapping = aes(x = `Total income: Mean`, y = `Crime rate (per 1000)`, label = `County`)) +
  geom_point() +
  scale_x_discrete(guide = guide_axis(n.dodge = 5)) + 
  labs(
    title = "Mean Income(£) vs Crime rate (Per 1000)",
    x = "Mean Income(£)",
    y = "Crime Rate (Per 1000)"
  ) + 
  geom_text(hjust = 0, vjust = 0)

### Median income vs crime rate

ggplot(data = df, mapping = aes(x = `Total income: Median`, y = `Crime rate (per 1000)`, label = `County`)) + 
  geom_point() + 
  scale_x_discrete(guide = guide_axis(n.dodge = 5)) + 
  labs(
    title = "Median Income(£) vs Crime Rate (Per 1000)",
    x = "Median Income(£)",
    y = "Crime Rate (Per 1000)"
  ) + 
  geom_text(hjust = 0, vjust = 0)

##################################

#### Other Crimes table

Crimes_County2 <- xlsx::read.xlsx("data/CSV/Crimes_County2.xlsx", sheetIndex = 2)
colnames(Crimes_County2) <- Crimes_County2[1,]

colnames(Crimes_County2)[4] = "Number"

Crimes_County2 <- Crimes_County2[-c(1,3)]
Crimes_County2 <- na.omit(Crimes_County2)
Crimes_County2 <- Crimes_County2 %>%
  filter(grepl("Total", `CSP`))

colnames(Crimes_County2)[1] <- "LC"

for(i in 1:nrow(Crimes_County2))
{
  Crimes_County2[i,][1] <- unlist(strsplit(as.character(Crimes_County2[i,][1]), split = " Total", fixed = TRUE))
}

Economic2 <- xlsx::read.xlsx("data/CSV/Weekly Pay.xlsx", sheetIndex = 2)

Economic2 <- na.omit(Economic2)

colnames(Economic2) <- Economic2[1,]
Economic2 <- Economic2[-c(1),]
colnames(Economic2)[1] <- c("LC") 

Economic2 <- Economic2 %>%
  filter(substr(`LC`, 1, 1) == " ")

for(i in c(1:nrow(Economic2)))
{
  Economic2[i,][1] <- unlist(strsplit(as.character(Economic2[i,][1]), split = " ", fixed = TRUE))[3]
}

pop_stats <-xlsx::read.xlsx("data/CSV/Population_Stats.xlsx", sheetIndex = 17)
pop_stats <- na.omit(pop_stats)
colnames(pop_stats) <- c("LC", "Population", "Median Age")

Crime_Factors <- left_join(Crimes_County2, Economic2, by = "LC")
Crime_Factors <- left_join(Crime_Factors, pop_stats, by = "LC")
Crime_Factors <- na.omit(Crime_Factors)

Crime_Factors <- Crime_Factors %>%
  mutate(Crime_rate = `Number`/`Population`)

Crime_Factors$Mean <- as.numeric(Crime_Factors$Mean) 
Crime_Factors$Median <- as.numeric(Crime_Factors$Median)

ggplot(data = Crime_Factors, mapping = aes(x = `Mean`, y = `Crime_rate`, label = `LC`)) + 
  geom_point() + 
  labs(
    title = "Mean weekly pay (£) vs Crime rate (By Local Authority)",
    x = "Mean weekly pay (£)",
    y = "Crime Rate (Crimes per Capita)"
  ) + 
    geom_smooth(method = lm, se = FALSE)


ggplot(data = Crime_Factors, mapping = aes(x = `Median`, y = `Crime_rate`, label = `LC`)) + 
  geom_point() + 
  labs(
    title = "Median weekly pay (£) vs Crime rate (By Local Authority)",
    x = "Median weekly pay (£)",
    y = "Crime Rate (Crimes per Capita)"
  ) + 
    geom_smooth(method = lm, se = FALSE)

##################################

### Poverty risk 

poverty_risk <- xlsx::read.xlsx("data/csv/poverty_risk.xlsx", sheetIndex = 1)

poverty_risk <- poverty_risk[c(1,3)]
colnames(poverty_risk) <- c("LC", "Poverty Risk") 

Crime_Factors <- left_join(Crime_Factors, poverty_risk, by = "LC")

Crime_Factors <- Crime_Factors %>%
  mutate(`Poverty Risk` = 327 - `Poverty Risk`)
## number of Local Authorities = 326

ggplot(data = Crime_Factors, mapping = aes(x = `Poverty Risk`, y = `Crime_rate`)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) + 
  labs(
    title = "Poverty Risk Vs Crime rate (By Local Authority)",
    x = "Poverty risk",
    y = "Crime Rate (Crimes per Capita)"
  )

cor.test(Crime_Factors$`Poverty Risk`, Crime_Factors$`Crime_rate`)

### unemployment rate

unemply_rate <- xlsx::read.xlsx("data/CSV/employmentlasewcensus2021.xlsx", sheetIndex = 2)

unemply_rate <- na.omit(unemply_rate)
colnames(unemply_rate) <- unemply_rate[1,]
unemply_rate <- unemply_rate[-c(1),]
unemply_rate <-unemply_rate[-c(3,4)]
unemply_rate <- unemply_rate %>%
  filter(`Economic activity (high-level) status` == "Unemployed")

unemply_rate <- unemply_rate[-c(1)]
colnames(unemply_rate) <- c("LC", "Unemployment Rate")
unemply_rate$`Unemployment Rate` <- as.numeric(unemply_rate$`Unemployment Rate`)

Crime_Factors <- left_join(Crime_Factors, unemply_rate, by = "LC")

ggplot(data = Crime_Factors, mapping = aes(x = `Unemployment Rate`, y = `Crime_rate`)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  labs(
    title = "Unemployment Rate Vs Crime rate (By Local Authority)",
    x = "Unemployment Rate",
    y = "Crime Rate (Crimes per Capita)"
  )
cor.test(Crime_Factors$`Unemployment Rate`, Crime_Factors$`Crime_rate`)

###### Divorce Rate

divorce_rate <- xlsx::read.xlsx("data/CSV/Divorce.xlsx", sheetIndex = 1)

divorce_rate <- divorce_rate[c(1,2)]
divorce_rate <- na.omit(divorce_rate)
divorce_rate <- divorce_rate[-c(1),]
colnames(divorce_rate) <- c("LC", "Divorce Rate")
divorce_rate$`Divorce Rate` <- as.numeric(divorce_rate$`Divorce Rate`) 

Crime_Factors <- left_join(Crime_Factors, divorce_rate, by = "LC")

ggplot(data = Crime_Factors, mapping = aes(x = `Divorce Rate`, y = `Crime_rate`)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) +
  labs(
    title = "Divorce Rate Vs Crime rate (By Local Authority)",
    x = "Divorce Rate",
    y = "Crime Rate (Crimes per Capita)"
  )
cor.test(Crime_Factors$`Divorce Rate`, Crime_Factors$`Crime_rate`)
#### Ethnic Minority Population

ethnic <- xlsx::read.xlsx("data/CSV/ethnic.xlsx", sheetIndex = 2)

ethnic <- ethnic[c(2, 5)]
ethnic <- na.omit(ethnic)
colnames(ethnic) <- c("LC", "White British %")
ethnic <- ethnic[-c(1),] 

for(i in c(1:nrow(ethnic)))
{
  new <- unlist(strsplit(as.character(ethnic[i,][1]), split = " ", fixed = TRUE))
  ethnic[i,][1] <- new[length(new)]
}

ethnic$`White British %` <- as.numeric(ethnic$`White British %`)

ethnic$`White British %` <- 1000 * ethnic$`White British %`

Crime_Factors <- left_join(Crime_Factors, ethnic, by = "LC")

Crime_Factors <- Crime_Factors %>%
  mutate(`White British %` = (`White British %`/`Population`) * 100)

Crime_Factors <- Crime_Factors %>%
  mutate(`Non White British %` = 100 - `White British %`)


ggplot(data = Crime_Factors, mapping = aes(x = `Non White British %`, y = `Crime_rate`, label = `LC`)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) + 
  labs(
    title = "% Ethnic Minority Population Vs Crime Rate (by Local Authority)",
       x = "% Non British White",
       y = "Crime Rate (Crimes per Capita)"
    )

cor.test(Crime_Factors$`Non White British %`, Crime_Factors$`Crime_rate`)

#Crime_Factors

### Religion

Religion <- xlsx::read.xlsx("data/CSV/ethnic.xlsx", sheetIndex = 3)

Religion <- Religion[c(2, 5, 12)]
Religion <- na.omit(Religion)

Religion <- Religion[-c(1),]
colnames(Religion) <-c("LC", "Christian", "Non-Religious")

for(i in c(1:nrow(Religion)))
{
  new <- unlist(strsplit(as.character(Religion[i,][1]), split = " ", fixed = TRUE))
  Religion[i,][1] <- new[length(new)]
}

Religion$`Christian` <- as.numeric(Religion$`Christian`)
Religion$`Non-Religious` <- as.numeric(Religion$`Non-Religious`)

Crime_Factors <- left_join(Crime_Factors, Religion, by = "LC")
Crime_Factors <- Crime_Factors %>%
  mutate(`% Minority Religion` = 100*(1 - (1000*(`Christian` + `Non-Religious`))/`Population`))

#Crime_Factors

ggplot(data = Crime_Factors, mapping = aes(x = `% Minority Religion`, y = `Crime_rate`)) + 
  geom_point() + 
  geom_smooth(method = lm, se = FALSE) + 
  labs(
    title = "% Non-Christian or Irreligious Vs Crime Rate (by Local Authority)",
       x = "% Non-Christian or Irreligious",
       y = "Crime Rate (Crimes per Capita)"
    )


cor.test(Crime_Factors$`% Minority Religion`, Crime_Factors$`Crime_rate`)

colnames(Crime_Factors)

#Re-scale Columns for gradient interpretation

cols <- c("Divorce Rate", "Poverty Risk", "Non White British %", "% Minority Religion", "Unemployment Rate")

for(x in c(1:length(cols)))
{
  Crime_Factors[cols[x]] <- Crime_Factors[cols[x]]/max(Crime_Factors[cols[x]])
}

Crime_Factors

### Model Testing/Training

set.seed(1234)
Crime_split <- initial_split(Crime_Factors)

Crime_train <- training(Crime_split)
Crime_test <- testing(Crime_split)

Crime_mod <- linear_reg() %>%
  set_engine("lm")

Crime_rec <- recipe(`Crime_rate` ~ ., data = Crime_train) 

Crime_rec <- Crime_rec %>%
  step_rm(`LC`, Number, Median, Mean, Population, `Median Age`, `Christian`, `White British %`, `Non-Religious`)

Crime_wflow <- workflow() %>%
  add_model(Crime_mod) %>%
  add_recipe(Crime_rec)

Crime_fit <- Crime_wflow %>%
  fit(data = Crime_train)

tidy(Crime_fit) %>%
  print()

Crime_train_pred <- predict(Crime_fit, Crime_train) %>%
  bind_cols(Crime_train %>% select(`Crime_rate`, `LC`))

Crime_train_pred
rmse(Crime_train_pred, truth = `Crime_rate`, estimate = .pred)

Crime_train %>%
  summarise(min = min(`Crime_rate`), max = max(`Crime_rate`))

Crime_test_pred <- predict(Crime_fit, Crime_test) %>%
  bind_cols(Crime_test %>% select(`Crime_rate`, `LC`))

Crime_test_pred
rmse(Crime_test_pred, truth = `Crime_rate`, estimate = .pred)

Crime_test_pred %>%
  summarise(min = min(`Crime_rate`), max = max(`Crime_rate`))

# tidy(Crime_mod) %>%
#   print(n = 12)

set.seed(789)

folds <- vfold_cv(Crime_train, v = 5)
Crime_fit_rs <- Crime_wflow %>%
  fit_resamples(folds)

collect_metrics(Crime_fit_rs)



```


```{R load-data}




################################################################

#might wanna turn on echo=false further down in the section as theres some real mountains of code
#that are just there to backup data and arent essential

################################################################

#############################

## comparison of demographics average time spent in solitary 



PunishmentsQ12023 <- read.csv("data/CSV/PunishmentsQ12023.csv")

Punishmentsminusna <- PunishmentsQ12023 %>% filter(No_of_days != ".")
Punishmentscellconfine <- Punishmentsminusna %>% filter(Punishment == "Cellular Confinement")
Punishmentsnumeric <- Punishmentscellconfine %>% mutate(No_of_days = as.numeric(No_of_days))

### ethnicity

solitaryethnicity <- Punishmentsnumeric %>% 
  group_by(Ethnicity) %>%
  summarise(
    mean_days_in_solitary = mean(No_of_days)
  )

ggplot(data = solitaryethnicity, mapping = aes(y = Ethnicity, x = mean_days_in_solitary)) +
  geom_bar(stat = "identity") +
  labs (
    y = "Ethnicity",
    x = "average days in solitary",
    title = "average time each ethnicity spends in solitary",
    subtitle = 
      "The average amount of time each ethnicity spends in solitary when sentenced to it as punishment whilst already incarcerated"
  )

## religion

solitaryreligion <- Punishmentsnumeric %>% 
  group_by(Religion) %>%
  summarise(
    mean_days_in_solitary = mean(No_of_days)
  )

ggplot(data = solitaryreligion, mapping = aes(y = Religion, x = mean_days_in_solitary)) +
  geom_bar(stat = "identity") +
  labs (
    y = "Religion",
    x = "average days in solitary",
    title = "average time each religion spends in solitary",
    subtitle = 
      "The average amount of time each religion spends in solitary when sentenced to it as punishment whilst already incarcerated"
  )

## age

solitaryage <- Punishmentsnumeric %>% 
  group_by(Age_group) %>%
  summarise(
    mean_days_in_solitary = mean(No_of_days)
  )

ggplot(data = solitaryage, mapping = aes(y = Age_group, x = mean_days_in_solitary)) +
  geom_bar(stat = "identity") +
  labs (
    y = "age",
    x = "average days in solitary",
    title = "average time an age group spends in solitary",
    subtitle = 
      "The average amount of time each age group spends in solitary when sentenced to it as punishment whilst already incarcerated"
  )

##sex

solitarysex <- Punishmentsnumeric %>% 
  group_by(Sex) %>%
  summarise(
    mean_days_in_solitary = mean(No_of_days)
  )

ggplot(data = solitarysex, mapping = aes(y = Sex, x = mean_days_in_solitary)) +
  geom_bar(stat = "identity") +
  labs (
    y = "sex",
    x = "average days in solitary",
    title = "average time wach sex spends in solitary",
    subtitle = 
      "The average amount of time each sex spends in solitary when sentenced to it as punishment whilst already incarcerated"
  )

###############################

#### percentage of demographics being Category A (high security)

## percentages can all be backed up by the mountain of code


categoryaethnicity <- data.frame(ethnicity = 
  c("Asian or Asian British", "Black/ African/ Caribbean/ Black British", "Mixed/ Multiple ethnic groups", "Other ethnic group", "White", "Not known"),
percentage = c(6.681351, 6.914817, 5.98262, 7.604563, 5.207938, 3.343465))


## mountain of code

c(
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Ethnicity == "a Asian or Asian British")) / count(filter(PunishmentsQ12023, Ethnicity == "a Asian or Asian British")) *100,
               count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Ethnicity == "b Black/ African/ Caribbean/ Black British")) / count(filter(PunishmentsQ12023, Ethnicity == "b Black/ African/ Caribbean/ Black British")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Ethnicity == "c Mixed/ Multiple ethnic groups")) / count(filter(PunishmentsQ12023, Ethnicity == "c Mixed/ Multiple ethnic groups")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Ethnicity == "d Other ethnic group")) / count(filter(PunishmentsQ12023, Ethnicity == "d Other ethnic group")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Ethnicity == "e White")) / count(filter(PunishmentsQ12023, Ethnicity == "e White")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Ethnicity == "f Not known")) / count(filter(PunishmentsQ12023, Ethnicity == "f Not known")) *100)
                      
ggplot(data = categoryaethnicity, mapping = aes(y = ethnicity, x = percentage)) +
  geom_bar(stat = "identity") +
  labs (
    y = "Ethnicity",
    x = "proportion of people in high security establishments (%)",
    title = "percentage of ethnicities considered to be high security risks",
  )


## age

categoryaage <- data.frame(age = 
  c("18 - 20", "21 - 24", "25 - 29", "30 - 39", "40 - 49", "50 - 59", "60 - 69", "70 and over", "15 - 17"),
percentage = c(2.037432, 5.839087, 5.979534, 6.93647, 6.37706, 7.416564, 4.709141, 9.722222, 0))


## mountain of code

c(
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "18 - 20")) / count(filter(PunishmentsQ12023, Age_group == "18 - 20")) *100,
               count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "21 - 24")) / count(filter(PunishmentsQ12023, Age_group == "21 - 24")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "25 - 29")) / count(filter(PunishmentsQ12023, Age_group == "25 - 29")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "30 - 39")) / count(filter(PunishmentsQ12023, Age_group == "30 - 39")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "40 - 49")) / count(filter(PunishmentsQ12023, Age_group == "40 - 49")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "50 - 59")) / count(filter(PunishmentsQ12023, Age_group == "50 - 59")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "60 - 69")) / count(filter(PunishmentsQ12023, Age_group == "60 - 69")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "70 and over")) / count(filter(PunishmentsQ12023, Age_group == "70 and over")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Age_group == "15 - 17")) / count(filter(PunishmentsQ12023, Age_group == "15 - 17")) *100)
                      
ggplot(data = categoryaage, mapping = aes(y = age, x = percentage)) +
  geom_bar(stat = "identity") +
  labs (
    y = "Age ranges",
    x = "proportion of people in high security establishments (%)",
    title = "percentage of age ranges considered to be high security risks",
  )

## religion

categoryareligion <- data.frame(religion = 
  c("Muslim", "No religion", "Christian", "Other religious groups", "Buddhist", "Jewish", "Sikh", "Hindu", "Not recorded"),
percentage = c(8.563744, 4.101825, 5.171328, 5.037783, 5.015198, 8.219178, 5.633803, 2.941176, 0))


## mountain of code

c(
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "b Muslim")) / count(filter(PunishmentsQ12023, Religion == "b Muslim")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "i No religion")) / count(filter(PunishmentsQ12023, Religion == "i No religion")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "a Christian")) / count(filter(PunishmentsQ12023, Religion == "a Christian")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "g Other religious groups")) / count(filter(PunishmentsQ12023, Religion == "g Other religious groups")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "e Buddhist")) / count(filter(PunishmentsQ12023, Religion == "e Buddhist")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "f Jewish")) / count(filter(PunishmentsQ12023, Religion == "f Jewish")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "d Sikh")) / count(filter(PunishmentsQ12023, Religion == "d Sikh")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "c Hindu")) / count(filter(PunishmentsQ12023, Religion == "c Hindu")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Religion == "j Not recorded")) / count(filter(PunishmentsQ12023, Religion == "j Not recorded")) *100)
  

ggplot(data = categoryareligion, mapping = aes(y = religion, x = percentage)) +
  geom_bar(stat = "identity") +
  labs (
    y = "Religion",
    x = "proportion of people in high security establishments (%)",
    title = "percentage of Religions considered to be high security risks",
  )


## Sex

categoryasex <- data.frame(sex = 
  c("Male", "Female"),
percentage = c(5.989141, 0))


## mountain of code

c(
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Sex == "M")) / count(filter(PunishmentsQ12023, Sex == "M")) *100,
  count(filter(PunishmentsQ12023, Predominant_function_of_establishment == "Category A (High Security)", Sex == "F")) / count(filter(PunishmentsQ12023, Sex == "F")) *100)

  

ggplot(data = categoryasex, mapping = aes(y = sex, x = percentage)) +
  geom_bar(stat = "identity") +
  labs (
    y = "Sex",
    x = "proportion of people in high security establishments (%)",
    title = "percentage of Religions considered to be high security risks",
  )

```
